export const ROUTES = {
    LOGIN: '/',
    DASHBOARD: "/dashboard/",
    LANGUAGES: "/languages/",
    PAGES: "/pages/",
    CONTENTS: "/contents/",
    WEBSITES: "/websites/",
    ANNOUNCEMENTS: "/announcements/",
    METATAGS: "/metatags/",
    BLOGS: "/blogs/",

    CREATE_LANGUAGE: "/create/language/",
    CREATE_PAGE: "/create/page/",
    CREATE_CONTENT: "/create/content/",
    CREATE_WEBSITE: "/create/website/",
    CREATE_ANNOUNCEMENT: "/create/announcement/",
    CREATE_METATAG: "/create/metatag/",
    CREATE_BLOGS: "/create/blogs/",

    UPDATE_LANGUAGE: "/update/language/:code/:webid/",
    UPDATE_PAGE: "/update/page/:id/",
    UPDATE_CONTENT: "/update/content/:id/",
    UPDATE_WEBSITE: "/update/website/:id/",
    UPDATE_ANNOUNCEMENT: "/update/announcement/:id/",
    UPDATE_METATAG: "/update/metatag/:id/",
    //RESET_PASS: '/resetpass/:id/:token/',
    //FORGOT_PASS: '/forgot-password',
    //RESET_PASS: '/reset-password/:token',
};